// How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

use num::bigint::BigInt;
use std::collections::HashSet;

// There's probably a way to do this my analysis
pub fn euler29() -> u64 {
    let mut h = HashSet::new();
    for a in 2..101 {
        for b in 2..101 {
            let x = BigInt::from(a);
            h.insert(x.pow(b as u32));
        }
    }
    return h.len() as u64;
}